name: compbeta-rocks

services:
  client:
    build:
      context: ..
      dockerfile: docker/Dockerfile.client
    image: compbeta-frontend:latest
    ports:
      - "5173:80"
    depends_on:
      - server
    networks:
      - app-network
    restart: unless-stopped

  server:
    build:
      context: ..
      dockerfile: docker/Dockerfile.server
    image: compbeta-api:latest
    ports:
      - "3000:3000"
    env_file:
      - ../server/.env.production
    networks:
      - app-network
    restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token eyJhIjoiYWMzMjAxYjY5M2JiYjNlNWU4OWVhNGQ2Yjg4MGIyYzkiLCJ0IjoiNmQyMWY5MDQtYTNiMy00ODA3LTkyODgtMmM5NTU0ZmJkMTI2IiwicyI6Ik9HRTBNakJpWW1ZdFpHRmlNeTAwTTJSbExXSXpNMkV0TmpnNVpUQm1ObVV3WVdWaiJ9
    environment:
      - 'NO_TLS_VERIFY=true'
      - 'TUNNEL_INGRESS_RULES={"https://compbeta.rocks":{"service":"http://client:80","originRequest":{"noTLSVerify":true}},"https://compbeta.rocks/api/*":{"service":"http://server:3000","originRequest":{"noTLSVerify":true}}}'
    depends_on:
      - client
      - server
    networks:
      - app-network
    restart: unless-stopped

secrets:
  cf_tunnel_token:
    file: ./secrets/cf_tunnel_token.txt

networks:
  app-network:
    driver: bridge