name: 🚀 Auto-Deploy to Droplet

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Droplet via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.DROPLET_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            set -e

            # Move into your Docker folder
            cd ~/ifsc-app/docker

            # Sync to latest main
            git fetch --all
            git reset --hard origin/main

            # Recreate .env from example + secrets
            cp .env.example .env
            cat > .env <<EOT
            PORT=${{ secrets.PORT }}
            MONGODB_URI=${{ secrets.MONGODB_URI }}
            DB_NAME=${{ secrets.DB_NAME }}
            GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
            GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}
            JWT_SECRET=${{ secrets.JWT_SECRET }}
            FRONTEND_URL=${{ secrets.FRONTEND_URL }}
            EOT

            # Store CF tunnel token securely
            mkdir -p ./secrets
            echo "${{ secrets.CF_TUNNEL_TOKEN }}" > ./secrets/cf_tunnel_token.txt
            chmod 600 ./secrets/cf_tunnel_token.txt

            # Pull any updated images & rebuild
            docker compose pull
            docker compose up -d --build
